# Generated by Django 6.0.1 on 2026-01-11 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayoutPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('bank', 'Bank Account'), ('nayapay', 'NayaPay'), ('sadapay', 'SadaPay'), ('jazzcash', 'JazzCash'), ('easypaisa', 'EasyPaisa'), ('raast', 'Raast')], default='bank', max_length=20)),
                ('account_title', models.CharField(blank=True, default='', max_length=120)),
                ('account_number', models.CharField(blank=True, default='', max_length=50)),
                ('iban', models.CharField(blank=True, default='', max_length=40)),
                ('raast_id', models.CharField(blank=True, default='', max_length=80)),
                ('phone_number', models.CharField(blank=True, default='', max_length=30)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payout_preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
