# Generated by Django 6.0.1 on 2026-01-11 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_payoutpreference'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funds_allocation_choice', models.CharField(blank=True, choices=[('return_bank', 'Return to my bank account'), ('donate_connected', 'Donate to connected fundraiser'), ('donate_expenses', 'Donate to website expenses'), ('keep', 'Keep it as it is')], default='', max_length=30)),
                ('is_deactivated', models.BooleanField(default=False)),
                ('is_closed', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account_setting', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_fundraiser_updates', models.BooleanField(default=True)),
                ('email_donation_received', models.BooleanField(default=True)),
                ('email_messages_from_donor', models.BooleanField(default=True)),
                ('email_connected_fundraisers', models.BooleanField(default=True)),
                ('msg_fundraiser_updates', models.BooleanField(default=False)),
                ('msg_donation_received', models.BooleanField(default=False)),
                ('msg_donation_confirmation', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
