# Generated by Django 6.0.1 on 2026-01-11 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_accountsetting_notificationpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsetting',
            name='cookies_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='accountsetting',
            name='otp_contact_number',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='accountsetting',
            name='two_step_verification',
            field=models.BooleanField(default=False),
        ),
    ]
