# Generated by Django 6.0.1 on 2026-01-11 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_accountsetting_cookies_enabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(blank=True, default='', max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('frequency_label', models.CharField(blank=True, default='', max_length=50)),
                ('status', models.CharField(choices=[('received', 'Received'), ('pending', 'Pending')], default='received', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations_received', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
