# Generated by Django 6.0.1 on 2026-01-11 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_donation_donor_fundraiser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fundraiser',
            old_name='total_received',
            new_name='collected_amount',
        ),
        migrations.AddField(
            model_name='fundraiser',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundraiser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='fundraisers/'),
        ),
        migrations.AddField(
            model_name='fundraiser',
            name='target_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='fundraiser',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('draft', 'Draft')], default='draft', max_length=20),
        ),
    ]
