# Generated by Django 6.0.1 on 2026-01-11 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_total_received_fundraiser_collected_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='fundraiser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='accounts.fundraiser'),
        ),
    ]
