# Generated by Django 6.0.1 on 2026-01-12 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_donation_fundraiser'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundraiser',
            name='bank_account_number',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='fundraiser',
            name='bank_account_title',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='fundraiser',
            name='bank_iban',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='fundraiser',
            name='bank_raast_id',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='fundraiser',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='fundraiser',
            name='location',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='fundraiser',
            name='payout_method',
            field=models.CharField(choices=[('bank', 'Bank Account'), ('nayapay', 'NayaPay'), ('sadapay', 'SadaPay'), ('jazzcash', 'JazzCash'), ('easypaisa', 'EasyPaisa'), ('raast', 'Raast')], default='bank', max_length=20),
        ),
        migrations.AddField(
            model_name='fundraiser',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundraiser',
            name='wallet_phone_number',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
