# Generated by Django 6.0.1 on 2026-01-12 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_fundraiser_bank_account_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundraiserDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='fundraiser_docs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('fundraiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='accounts.fundraiser')),
            ],
        ),
    ]
