# Generated by Django 6.0.1 on 2026-01-12 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_fundraiserdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundraiserPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('bank', 'Bank Account'), ('nayapay', 'NayaPay'), ('sadapay', 'SadaPay'), ('jazzcash', 'JazzCash'), ('easypaisa', 'EasyPaisa'), ('raast', 'Raast')], max_length=20)),
                ('is_enabled', models.BooleanField(default=False)),
                ('bank_account_title', models.CharField(blank=True, default='', max_length=120)),
                ('bank_account_number', models.CharField(blank=True, default='', max_length=60)),
                ('bank_iban', models.CharField(blank=True, default='', max_length=50)),
                ('bank_raast_id', models.CharField(blank=True, default='', max_length=80)),
                ('phone_number', models.CharField(blank=True, default='', max_length=30)),
                ('fundraiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='accounts.fundraiser')),
            ],
            options={
                'unique_together': {('fundraiser', 'method')},
            },
        ),
    ]
