# Generated by Django 6.0.1 on 2026-01-14 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_fundraiserpayout'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundraiser',
            name='donee_education_level',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='fundraiser',
            name='donee_gender',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='fundraiser',
            name='donee_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='fundraiser',
            name='fundraiser_purpose',
            field=models.CharField(blank=True, choices=[('child_student', 'Support a child/student'), ('institution', 'Support an institution'), ('organization', 'Support an organization')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='fundraiser',
            name='institution_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='fundraiser',
            name='institution_registration_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='fundraiser',
            name='institution_type',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
    ]
