# Generated by Django 6.0.1 on 2026-01-14 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_fundraiser_donee_education_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundraiser',
            name='category',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
