# Generated by Django 6.0.1 on 2026-01-14 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_fundraiser_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundraiser',
            name='linked_fundraiser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_children', to='accounts.fundraiser'),
        ),
    ]
