# Generated by Django 6.0.1 on 2026-01-14 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_fundraiser_linked_fundraiser'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundraiser',
            name='reimbursement_period',
            field=models.CharField(blank=True, choices=[('3_days', '3 days'), ('7_days', '7 days'), ('15_days', '15 days'), ('30_days', '30 days'), ('on_deadline', 'On deadline')], default='', max_length=20),
        ),
    ]
