# Generated by Django 6.0.1 on 2026-01-15 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_donation_is_anonymous_donation_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='card_expiry',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='donation',
            name='card_holder_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='donation',
            name='card_number_last4',
            field=models.CharField(blank=True, default='', max_length=4),
        ),
        migrations.AddField(
            model_name='donation',
            name='payer_phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
