from django.urls import path
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView
from .views import SignupView, ProfileView, AvatarUploadView
from .views import (
    PasswordResetStartView,
    PasswordResetResendView,
    PasswordResetVerifyView,
    PasswordResetCompleteView,
    SignupView, ProfileView, AvatarUploadView,
    NotificationPreferenceView, AccountSettingView,
    ChangePasswordView, DeactivateAccountView, CloseAccountView,
    BalanceView, DashboardView, MyFundraisersView,
    FundraiserDetailView, FundraiserDonationsView, FundraiserCloseView,
    FundraiserEditView,
    FundraiserCoverUploadView,
    FundraiserDocumentUploadView,
    FundraiserDocumentDeleteView,
    MyDonationsView, FundraiserStartDetailsView, StartFundraiserView,
    FundraiserBasicView, FundraiserDetailsView,
    MyActiveFundraisersView, FundraiserLinkPreviousView,
    FundraiserPayoutSetupView, FundraiserPublishView,
    FeaturedFundraisersView, FundraiserCategoriesView, FundraiserDiscoverView,
    FundraiserPublicDetailView, FundraiserDonateCreateView,
)

urlpatterns = [
    path("signup/", SignupView.as_view(), name="signup"),
    path("login/", TokenObtainPairView.as_view(), name="login"),      # username + password
    path("refresh/", TokenRefreshView.as_view(), name="refresh"),
    path("me/", ProfileView.as_view(), name="me"),
    path("me/avatar/", AvatarUploadView.as_view(), name="avatar"),
    path("password-reset/start/", PasswordResetStartView.as_view()),
    path("password-reset/resend/", PasswordResetResendView.as_view()),
    path("password-reset/verify/", PasswordResetVerifyView.as_view()),
    path("password-reset/complete/", PasswordResetCompleteView.as_view()),
    path("settings/notifications/", NotificationPreferenceView.as_view()),
    path("settings/account/", AccountSettingView.as_view()),
    path("change-password/", ChangePasswordView.as_view()),
    path("deactivate/", DeactivateAccountView.as_view()),
    path("close/", CloseAccountView.as_view()),
    path("balance/", BalanceView.as_view()),
    path("dashboard/", DashboardView.as_view()),
    path("dashboard/my-fundraisers/", MyFundraisersView.as_view()),
    path("fundraisers/<int:fundraiser_id>/", FundraiserDetailView.as_view()),
    path("fundraisers/<int:fundraiser_id>/donations/", FundraiserDonationsView.as_view()),
    path("fundraisers/<int:fundraiser_id>/close/", FundraiserCloseView.as_view()),
    path("fundraisers/<int:fundraiser_id>/edit/", FundraiserEditView.as_view()),
    path("fundraisers/<int:fundraiser_id>/edit/cover/", FundraiserCoverUploadView.as_view()),
    path("fundraisers/<int:fundraiser_id>/edit/documents/", FundraiserDocumentUploadView.as_view()),
    path("fundraisers/<int:fundraiser_id>/edit/documents/<int:doc_id>/", FundraiserDocumentDeleteView.as_view()),
    path("dashboard/my-donations/", MyDonationsView.as_view()),
    path("fundraisers/start/", StartFundraiserView.as_view(), name="fundraiser-start"),
    path("fundraisers/<int:fundraiser_id>/start-details/", FundraiserStartDetailsView.as_view(), name="fundraiser-start-details"),
    path("fundraisers/<int:fundraiser_id>/basic/", FundraiserBasicView.as_view(), name="fundraiser-basic"),
    path("fundraisers/<int:fundraiser_id>/details/", FundraiserDetailsView.as_view(), name="fundraiser-details"),
    path("fundraisers/active/", MyActiveFundraisersView.as_view(), name="my-active-fundraisers"),
    path("fundraisers/<int:fundraiser_id>/link-previous/", FundraiserLinkPreviousView.as_view(), name="link-previous"),
    path("fundraisers/<int:fundraiser_id>/payout-setup/", FundraiserPayoutSetupView.as_view(), name="fundraiser-payout-setup"),
    path("fundraisers/<int:fundraiser_id>/publish/", FundraiserPublishView.as_view(), name="fundraiser-publish"),
    path("fundraisers/featured/", FeaturedFundraisersView.as_view(), name="featured-fundraisers"),
    path("fundraisers/categories/", FundraiserCategoriesView.as_view()),
    path("fundraisers/discover/", FundraiserDiscoverView.as_view()),
    path("fundraisers/<int:fundraiser_id>/public/", FundraiserPublicDetailView.as_view()),
    path("fundraisers/<int:fundraiser_id>/donate/", FundraiserDonateCreateView.as_view()),
]
